#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean MHDPimple
wclean MHDPimpleAverage
wclean MHDSimple
wclean MHDSimpleBounded

# ----------------------------------------------------------------- end-of-file
