#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake MHDPimple
wmake MHDPimpleAverage
wmake MHDSimple
wmake MHDSimpleBounded

# ----------------------------------------------------------------- end-of-file
